services:
  bottst:
    build: .
    container_name: notify
    ports:
      - "54822:54822"
    environment:
      # енвы подключения к БД
      - CONFIG_PATH=config/config.local.docker.yaml
    networks:
      - default
networks:
  default:
    external: true
    name: risp
