env: "prod"

minio:
  endpoint: "minio:9000"
  accessKey: "minioadmin"
  secretKey: "minioadmin"
  useSsl: false
  bucket: "images"
  urlExpiry: "15m"

db:
  type: "postgres"
  port: 5434
  host: "menu_db"
  user: "postgres"
  password: "postgres"
  name: "menu"
  sslMode: "disable"
  poolMaxConn: 20
  poolMaxConnLifetime: "2h"

grpcServer:
  address: "localhost"
  port: 50052

telemetry:
  serviceName: "menu-service"
  serviceVersion: "1.0.0"
  environment: "production"
  metricsPort: 10003
  traceEndpoint: "jaeger:4317"
