receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
  resource:
    attributes:
      - key: service.namespace
        value: "restaurant_is"
        action: upsert
      - key: deployment.environment
        value: "production"
        action: upsert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889" # Изменено с 8888 на 8889
    namespace: "restaurant_is"
  zipkin:
    endpoint: "http://jaeger:9411/api/v2/spans"
    format: proto
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, prometheus]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, zipkin]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug]
