services:
  auth_service:
    build: ./auth
    container_name: auth_service
    ports:
      - "54821:54821"
    environment:
      - CONFIG_PATH=config/config.local.yaml
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
  notify:
    build: ./notify
    container_name: notify
    ports:
      - "54822:54822"
    environment:
      # енвы подключения к БД
      - CONFIG_PATH=config/config.local.docker.yaml
    networks:
      - default
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    command: postgres
    volumes:
      - ./migrations/pg/init.sql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
networks:
  default:
    name: risp
