services:
  auth_service:
    build: .
    container_name: auth_service
    ports:
      - "54821:8080"
    environment:
      - CONFIG_PATH=config/local.yaml
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bottst
    ports:
      - "5432:5432"
    command: postgres
    volumes:
      - ./internal/database/migrations/init.sql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

networks:
  internal:
    name: auth_service
