global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "auth_service"
    static_configs:
      - targets: ["auth_service:10001"]
    metrics_path: "/metrics"
    scrape_interval: 10s
  - job_name: "notify"
    static_configs:
      - targets: ["notify:10004"]
    metrics_path: "/metrics"
    scrape_interval: 10s
  - job_name: "menu_service"
    static_configs:
      - targets: ["menu_service:10003"]
    metrics_path: "/metrics"
    scrape_interval: 10s
  - job_name: "order_service"
    static_configs:
      - targets: ["order_service:10005"]
    metrics_path: "/metrics"
    scrape_interval: 10s
  - job_name: "user_service"
    static_configs:
      - targets: ["user_service:10006"]
    metrics_path: "/metrics"
    scrape_interval: 10s
  - job_name: "gate"
    static_configs:
      - targets: ["gate:8080"]
    metrics_path: "/metrics"
    scrape_interval: 10s
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"] # Изменено с 8888 на 8889
    metrics_path: "/metrics"
    scrape_interval: 10s
