global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Auth Service
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:54821']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Notify Service
  - job_name: 'notify'
    static_configs:
      - targets: ['notify:54822']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Menu Service
  - job_name: 'menu_service'
    static_configs:
      - targets: ['menu_service:50052']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Order Service
  - job_name: 'order_service'
    static_configs:
      - targets: ['order_service:50051']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # User Service
  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service:50045']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Gate Service
  - job_name: 'gate'
    static_configs:
      - targets: ['gate:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL databases (if they expose metrics)
  - job_name: 'user_db'
    static_configs:
      - targets: ['user_db:5439']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'auth_db'
    static_configs:
      - targets: ['auth_db:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'menu_db'
    static_configs:
      - targets: ['menu_db:5434']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'order_db'
    static_configs:
      - targets: ['order_db:5435']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  # Kafka (if JMX exporter is configured)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9404']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Zookeeper (if JMX exporter is configured)
  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:9404']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Metabase
  - job_name: 'metabase'
    static_configs:
      - targets: ['metabase:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s