services:
  auth_service:
    build: .
    image: netscrawler/auth-service:latest
    container_name: auth_service
    ports:
      - "54821:54821"
    environment:
      - CONFIG_PATH=/auth/config/config.local.yaml
    volumes:
      - ./config:/auth/config:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    command: postgres
    volumes:
      - ./migrations/pg/init.sql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
  default:
    name: risp
