services:
  menu_service:
    build: .
    container_name: menu_service
    ports:
      - "50052:50052"
      - "9090:9090"
    environment:
      - CONFIG_PATH=/menu/config/config.local.yaml
    volumes:
      - ./config:/menu/config
    depends_on:
      menu_db:
        condition: service_healthy
    networks:
      - default

  menu_db:
    image: postgres:latest
    container_name: menu_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: menu
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: postgres -p 5433
    volumes:
      - ./migrations/pg/init.sql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  minio-data:

networks:
  default:
    name: risp
