server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels:
          [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            time: time
            level: level
            msg: msg
            channel: channel
            method: method
            request: request
            response: response
            trace_id: trace_id
            recipient: recipient
            query: query
            headers: headers
            body: body
            client_ip: client_ip
            user_agent: user_agent
            host: host
            proto: proto
            message: message
            status: status
            latency: latency
            path: path
            service: service
            storage: storage
            func: func
            bucket: bucket
            addr: addr
            server: server
            content_type: content_type
      - labels:
          level: level
          msg: msg
          channel: channel
          method: method
          request: request
          response: response
          trace_id: trace_id
          recipient: recipient
          query: query
          headers: headers
          body: body
          client_ip: client_ip
          user_agent: user_agent
          host: host
          proto: proto
          message: message
          status: status
          latency: latency
          path: path
          service: service
          storage: storage
          func: func
          bucket: bucket
          addr: addr
          server: server
          content_type: content_type

      - timestamp:
          source: time
          format: RFC3339Nano
