env: "dev"

db:
  type: "postgres"
  port: 5439
  host: "user_db"
  user: "postgres"
  password: "postgres"
  name: "user"
  sslMode: "disable"
  poolMaxConn: 20
  poolMaxConnLifetime: "2h"

grpcServer:
  address: "localhost"
  port: 50045

telemetry:
  serviceName: "user-service"
  serviceVersion: "1.0.0"
  environment: "production"
  metricsPort: 9095
  traceEndpoint: "jaeger:4317"
