server:
  host: "0.0.0.0"
  port: 8080

auth:
  jwt_secret: "your-secret-key"

services:
  auth:
    host: "auth_service"
    port: 54821
  user:
    host: "user_service"
    port: 50045
  menu:
    host: "menu_service"
    port: 50052
  order:
    host: "order_service"
    port: 50051
  notify:
    host: "notify"
    port: 54822

telemetry:
  serviceName: "gate"
  serviceVersion: "1.0.0"
  environment: "production"
  metricsPort: 10002
  traceEndpoint: "jaeger:4317"
