env: "local"

db:
  type: "postgres"
  port: 5432
  host: "db"
  user: "postgres"
  password: "postgres"
  name: "menu"
  sslMode: "disable"
  poolMaxConn: 20
  poolMaxConnLifetime: "2h"

grpcServer:
  address: ":54821"
  port: 54821
